// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwDmoeTJhwFU2qrneXCBtQVt4q0R9kVY',
    appId: '1:592366326939:web:b14550f0ef8e377bb6e23e',
    messagingSenderId: '592366326939',
    projectId: 'testfirebase-e0e2f',
    authDomain: 'testfirebase-e0e2f.firebaseapp.com',
    storageBucket: 'testfirebase-e0e2f.appspot.com',
    measurementId: 'G-L1T2RS6Z13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJFyZhoKoUAIYBFmVp0jD5AUG7rkKYzKk',
    appId: '1:592366326939:android:809f9c9fb107096db6e23e',
    messagingSenderId: '592366326939',
    projectId: 'testfirebase-e0e2f',
    storageBucket: 'testfirebase-e0e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Q0wPG97WTccDmmStp0NnTzflwy6Oyk8',
    appId: '1:592366326939:ios:99aaf7380affb896b6e23e',
    messagingSenderId: '592366326939',
    projectId: 'testfirebase-e0e2f',
    storageBucket: 'testfirebase-e0e2f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Q0wPG97WTccDmmStp0NnTzflwy6Oyk8',
    appId: '1:592366326939:ios:99aaf7380affb896b6e23e',
    messagingSenderId: '592366326939',
    projectId: 'testfirebase-e0e2f',
    storageBucket: 'testfirebase-e0e2f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjwDmoeTJhwFU2qrneXCBtQVt4q0R9kVY',
    appId: '1:592366326939:web:829ea929424c4768b6e23e',
    messagingSenderId: '592366326939',
    projectId: 'testfirebase-e0e2f',
    authDomain: 'testfirebase-e0e2f.firebaseapp.com',
    storageBucket: 'testfirebase-e0e2f.appspot.com',
    measurementId: 'G-YJ4NSRJKER',
  );
}
